kind: Deployment
apiVersion: apps/v1
metadata:
  name: openldap
  labels:
    app: openldap
    app.kubernetes.io/component: openldap
    app.kubernetes.io/instance: openldap
    app.kubernetes.io/name: openldap
    app.kubernetes.io/part-of: docker-app
    app.openshift.io/runtime-namespace: ldap-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openldap
  template:
    metadata:
      labels:
        app: openldap
        deploymentconfig: openldap
    spec:
      containers:
        - name: openldap
          image: docker.io/bitnami/openldap
          ports:
            - containerPort: 1389
              protocol: TCP
            - containerPort: 1636
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
