- name: Evaluate OpenLDAP Instance
  k8s:
    state: present
    namespace: '{{ demo_project }}'
    resource_definition: "{{ lookup('file', 'deployment.yaml') }}"

- name: Evaluate OpenLDAP Service
  k8s:
    state: present
    namespace: '{{ demo_project }}'
    resource_definition: "{{ lookup('file', 'service.yaml') }}"
